"""add missing columns

Revision ID: 6b9efbe6daff
Revises: d66d512d4385
Create Date: 2026-05-13 11:20:37.803851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9efbe6daff'
down_revision: Union[str, Sequence[str], None] = 'd66d512d4385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('intent', sa.String(length=50), nullable=True))
    op.add_column('query_logs', sa.Column('sentiment', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('company_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'company_type')
    op.drop_column('query_logs', 'sentiment')
    op.drop_column('query_logs', 'intent')
    # ### end Alembic commands ###
